project_id = "sdvakfhmoaoucmhbhwvy"

[api]
enabled = true
url = "https://sdvakfhmoaoucmhbhwvy.supabase.co/functions/v1"

[[headers]]
for = "/get-manual-valuation"
values = { Access-Control-Allow-Origin = "*" }