project_id = "sdvakfhmoaoucmhbhwvy"

[api]
enabled = true
max_rows = 1000

[[edge_functions]]
name = "process-image"
verify_jwt = true

[[edge_functions]]
name = "handle-car-listing"
verify_jwt = true

[[edge_functions]]
name = "send-dealer-welcome"
verify_jwt = true

[[edge_functions]]
name = "email-templates"
verify_jwt = true

[[edge_functions]]
name = "send-email"
verify_jwt = true

[[edge_functions]]
name = "get-vehicle-valuation"
verify_jwt = true