
# Project configuration
project_id = "wdayevpcyrmdftsxrvwx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

# Edge Function configuration
[functions]
enabled = true

[functions.get-vehicle-valuation]
verify_jwt = false
