
# This file is used to configure your Supabase project.
# Shared production settings
project_id = "sdvakfhmoaoucmhbhwvy"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single REST request.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[functions]
# Port to use for Functions API URL.
port = 54323

[functions.validate-vin]
verify_jwt = true

[functions.validate-vin.environment]
VALUATION_API_ID = "AUTOSTRA"
VALUATION_API_SECRET = "A4FTFH54C3E37P2D34A16A7A4V41XKBF"

[studio]
# Port to use for Supabase Studio.
port = 54324

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54325
smtp_port = 54326
pop3_port = 54327
